
interface Iproduct {
    id: number
    name: string,
    price: number,
    category: string,
    size: string[] | null,
    quantity: number,
    image: string[],
    tag?: string[],
    description?: string,
}

const category = ["men", "women", "accessory"];
const size = ["S", "M", "L", "XL"]
export let productData: Iproduct[] = [
    {
        id: 1,
        name: "Basic White Tee",
        price: 10,
        category: "men",
        size: size,
        quantity: 100,
        image: [
            "basic_white_tee_1.webp",
            "basic_white_tee_2.webp",
            "basic_white_tee_preview_1.webp"
        ],
    },
    {
        id: 2,
        name: "Basic Black Tee",
        price: 10,
        category: "men",
        size: size,
        quantity: 100,
        image: [
            "basic_black_tee_1.webp",
            "basic_black_tee_2.webp",
            "basic_black_tee_preview_1.webp"
        ],
    },
    {
        id: 3,
        name: "Black Shirt",
        price: 20,
        category: "men",
        size: size,
        quantity: 100,
        image: [
            "black_shirt_1.webp",
            "black_shirt_2.webp",
            "black_shirt_preview_1.webp",
            "black_shirt_preview_2.webp",
            "black_shirt_preview_3.webp"
        ],
    },
    {
        id: 4,
        name: "The Path T-Shirt",
        price: 15,
        category: "men",
        size: size,
        quantity: 100,
        image: [
            "thepath_1.webp",
            "thepath_2.webp",
            "thepath_preview_1.webp",
            "thepath_preview_2.webp",
            "thepath_preview_3.webp"
        ],
    },
    {
        id: 5,
        name: "White Shirt",
        price: 20,
        category: "men",
        size: size,
        quantity: 100,
        image: [
            "black_shirt_1.webp",
            "black_shirt_2.webp",
            "black_shirt_preview_1.webp",
            "black_shirt_preview_2.webp",
            "black_shirt_preview_3.webp",
            "black_shirt_preview_4.webp"
        ],
    },
    {
        id: 6,
        name: "Young Asian T-Shirt",
        price: 15,
        category: "men",
        size: size,
        quantity: 100,
        image: [
            "young_asian_1.webp",
            "young_asian_2.webp",
            "young_asian_preview_1.webp",
            "young_asian_preview_2.webp",
        ],
    },
    {
        id: 7,
        name: "YOLO Black Hoodie",
        price: 30,
        category: "",
        size: size,
        quantity: 100,
        image: [
            "black_hoodie_1.webp",
            "black_hoodie_2.webp",
            "black_hoodie_preview_1.webp",
            "black_hoodie_preview_2.webp",
        ],
    },
    {
        id: 8,
        name: "SCHDTX Hoodie",
        price: 30,
        category: "men",
        size: size,
        quantity: 100,
        image: [
            "SCHDTX_1.webp",
            "SCHDTX_2.webp",
            "SCHDTX_preview_1.webp",
            "SCHDTX_preview_2.webp",
            "SCHDTX_preview_3.webp"
        ],
    },
    {
        id: 9,
        name: "Tie dye WindBreaker Hoodie",
        price: 40,
        category: "men",
        size: size,
        quantity: 100,
        image: [
            "tiedye_windbreaker_1.webp",
            "tiedye_windbreaker_2.webp",
            "tiedye_windbreaker_preview_1.webp",
            "tiedye_windbreaker_preview_2.webp",
            "tiedye_windbreaker_preview_3.webp"
        ],
    },
    {
        id: 10,
        name: "Signature Hoodie",
        price: 40,
        category: "women",
        size: size,
        quantity: 100,
        image: [
            "yellow_hoodie_1.webp",
            "yellow_hoodie_2.webp",
            "yellow_hoodie_preview_1.webp",
            "yellow_hoodie_preview_2.webp",
            "yellow_hoodie_preview_3.webp"
        ],
    },
    {
        id: 11,
        name: "Basic Black Shorts",
        price: 10,
        category: "men",
        size: size,
        quantity: 100,
        image: [
            "basic_black_shorts_1.webp",
            "basic_black_shorts_2.webp",
            "basic_black_shorts_preview_1.webp",
            "basic_black_shorts_preview_2.webp",
            "basic_black_shorts_preview_3.webp"
        ],
    },
    {
        id: 12,
        name: "Basic White Shorts",
        price: 12,
        category: "men",
        size: size,
        quantity: 100,
        image: [
            "basic_white_shorts_1.webp",
            "basic_white_shorts_2.webp",
            "basic_white_shorts_preview_1.webp",
            "basic_white_shorts_preview_2.webp",
            "basic_white_shorts_preview_3.webp"
        ],
    },
    {
        id: 13,
        name: "Black Fashion Jogger",
        price: 20,
        category: "men",
        size: size,
        quantity: 100,
        image: [
            "black_jogger_1.webp",
            "black_jogger_2.webp",
            "black_jogger_preview_1.webp",
            "black_jogger_preview_2.webp",
            "black_jogger_preview_3.webp"
        ],
    },
    {
        id: 14,
        name: "Yellow Jogger",
        price: 20,
        category: "men",
        size: size,
        quantity: 100,
        image: [
            "yellow_jogger_1.webp",
            "yellow_jogger_2.webp",
            "yellow_jogger_preview_1.webp",
            "yellow_jogger_preview_2.webp",
        ],
    },
    {
        id: 15,
        name: "Black Shorts - The Path",
        price: 15,
        category: "men",
        size: size,
        quantity: 100,
        image: [
            "black_shorts_thepath_1.webp",
            "black_shorts_thepath_2.webp",
            "black_shorts_thepath_preview_1.webp",
            "black_shorts_thepath_preview_2.webp",
            "black_shorts_thepath_preview_3.webp"
        ],
    },
    {
        id: 16,
        name: "Blue Shorts",
        price: 10,
        category: "men",
        size: size,
        quantity: 100,
        image: [
            "blue_shorts_1.webp",
            "blue_shorts_2.webp",
            "blue_shorts_preview_1.webp",
            "blue_shorts_preview_2.webp",
            "blue_shorts_preview_3.webp"
        ],
    },
    {
        id: 17,
        name: "Cordugoy Pants",
        price: 15,
        category: "men",
        size: size,
        quantity: 100,
        image: [
            "cordugoy_pants_1.webp",
            "cordugoy_pants_2.webp",
            "cordugoy_pants_preview_1.webp",
            "cordugoy_pants_preview_2.webp",
            "cordugoy_pants_preview_3.webp",
            "cordugoy_pants_preview_4.webp"
        ],
    },
    {
        id: 18,
        name: "Formal Long Trousers",
        price: 25,
        category: "men",
        size: size,
        quantity: 100,
        image: [
            "long_trousers_1.webp",
            "long_trousers_2.webp",
            "long_trousers_preview_1.webp",
            "long_trousers_preview_2.webp",
            "long_trousers_preview_3.webp",
            "long_trousers_preview_4.webp",
            "long_trousers_preview_5.webp",
        ],
    },
    {
        id: 19,
        name: "Black Track Pants",
        price: 20,
        category: "men",
        size: size,
        quantity: 100,
        image: [
            "track_pants_1.webp",
            "track_pants_2.webp",
            "track_pants_preview_1.webp",
            "track_pants_preview_2.webp",
            "track_pants_preview_3.webp",
            "track_pants_preview_4.webp",
        ],
    },
    {
        id: 20,
        name: "White Track Pants",
        price: 20,
        category: "men",
        size: size,
        quantity: 100,
        image: [
            "white_track_pants_1.webp",
            "white_track_pants_2.webp",
            "white_track_pants_preview_1.webp",
            "white_track_pants_preview_2.webp",
            "white_track_pants_preview_3.webp",
            "white_track_pants_preview_4.webp",
        ],
    },
    {
        id: 21,
        name: "Westside Shorts",
        price: 15,
        category: "men",
        size: size,
        quantity: 100,
        image: [
            "westside_shorts_1.webp",
            "westside_shorts_2.webp",
            "westside_shorts_preview_1.webp",
            "westside_shorts_preview_2.webp",
            "westside_shorts_preview_3.webp",
        ],
    },
    {
        id: 22,
        name: "Family Cap",
        price: 10,
        category: "accessory",
        size: size,
        quantity: 50,
        image: [
            "family_cap_1.webp",
            "family_cap_2.webp",
            "family_cap_3.webp",
        ],
    },
    {
        id: 23,
        name: "High top Beanine",
        price: 13,
        category: "accessory",
        size: size,
        quantity: 50,
        image: [
            "high_top_beanie_1.webp",
            "high_top_beanie_2.webp",
            "high_top_beanie_3.webp",
            "high_top_beanie_4.webp",
            "high_top_beanie_5.webp",
        ],
    },
    {
        id: 24,
        name: "Skull Beanie - Blue Edition",
        price: 15,
        category: "accessory",
        size: size,
        quantity: 50,
        image: [
            "skull_beanie_blue_1.webp",
            "skull_beanie_blue_2.webp",
            "skull_beanie_blue_3.webp",
            "skull_beanie_blue_4.webp",
        ],
    },
    {
        id: 25,
        name: "Skull Beanie - Orange Edition",
        price: 15,
        category: "accessory",
        size: size,
        quantity: 50,
        image: [
            "skull_beanie_orange_1.webp",
            "skull_beanie_orange_2.webp",
            "skull_beanie_orange_3.webp",
            "skull_beanie_orange_4.webp",
        ],
    },
    {
        id: 26,
        name: "Original Cap - Yellow",
        price: 10,
        category: "accessory",
        size: size,
        quantity: 50,
        image: [
            "original_cap_yellow_1.webp",
            "original_cap_yellow_2.webp",
            "original_cap_yellow_3.webp",
        ],
    },
    {
        id: 27,
        name: "SCHDTX Cap",
        price: 15,
        category: "accessory",
        size: size,
        quantity: 50,
        image: [
            "schdtx_cap_1.webp",
            "schdtx_cap_2.webp",
            "schdtx_cap_3.webp",
            "schdtx_cap_4.webp",
        ],
    },
    {
        id: 28,
        name: "SCHDTX Cap - White",
        price: 15,
        category: "accessory",
        size: size,
        quantity: 50,
        image: [
            "schdtx_cap_white_1.webp",
            "schdtx_cap_white_2.webp",
            "schdtx_cap_white_3.webp",
            "schdtx_cap_white_4.webp",
        ],
    },
    {
        id: 29,
        name: "Messenger Bag",
        price: 60,
        category: "accessory",
        size: null,
        quantity: 50,
        image: [
            "messenger_bag_1.webp",
            "messenger_bag_2.webp",
            "messenger_bag_3.webp",
            "messenger_bag_4.webp",
            "messenger_bag_5.webp",
            "messenger_bag_6.webp",
        ],
    },
    {
        id: 30,
        name: "Shoulder bag - Black Colorway",
        price: 35,
        category: "accessory",
        size: null,
        quantity: 50,
        image: [
            "shoulder_bag_black_1.webp",
            "shoulder_bag_black_2.webp",
            "shoulder_bag_black_3.webp",
            "shoulder_bag_black_4.webp",
            "shoulder_bag_black_5.webp",
        ],
    },
    {
        id: 31,
        name: "Shoulder bag - Cream Colorway",
        price: 35,
        category: "accessory",
        size: null,
        quantity: 50,
        image: [
            "shoulder_bag_cream_1.webp",
            "shoulder_bag_cream_2.webp",
            "shoulder_bag_cream_3.webp",
            "shoulder_bag_cream_4.webp",
            "shoulder_bag_cream_5.webp",
        ],
    },
    {
        id: 32,
        name: "Westside Crossbody Sporty Bag",
        price: 30,
        category: "accessory",
        size: null,
        quantity: 50,
        image: [
            "westside_crossbody_1.webp",
            "westside_crossbody_2.webp",
            "westside_crossbody_3.webp",
            "westside_crossbody_4.webp",
            "westside_crossbody_5.webp",
        ],
    },
    {
        id: 33,
        name: "StyleShop's Signature Backpack",
        price: 120,
        category: "accessory",
        size: null,
        quantity: 50,
        image: [
            "backpack_1.webp",
            "backpack_2.webp",
            "backpack_3.webp",
            "backpack_4.webp",
            "backpack_5.webp",
        ],
    },
    {
        id: 34,
        name: "Black Kaki Dress",
        price: 20,
        category: "women",
        size: size,
        quantity: 100,
        image: [
            "black_kaki_dress_1.webp",
            "black_kaki_dress_2.webp",
            "black_kaki_dress_3.webp",
            "black_kaki_dress_4.webp",
        ],
    },
    {
        id: 35,
        name: "Flower Pattern Dress",
        price: 15,
        category: "women",
        size: size,
        quantity: 100,
        image: [
            "flower_dress_1.webp",
            "flower_dress_2.webp",
            "flower_dress_3.webp",
            "flower_dress_4.webp",
        ],
    },
    {
        id: 36,
        name: "Yellow Twist Dress",
        price: 20,
        category: "women",
        size: size,
        quantity: 100,
        image: [
            "yellow_twist_dress_1.webp",
            "yellow_twist_dress_2.webp",
            "yellow_twist_dress_3.webp",
            "yellow_twist_dress_4.webp",
        ],
    },
    {
        id: 37,
        name: "Party Dress - Flower Pattern",
        price: 45,
        category: "women",
        size: size,
        quantity: 100,
        image: [
            "party_dress_flower_1.webp",
            "party_dress_flower_2.webp",
            "party_dress_flower_3.webp",
            "party_dress_flower_4.webp",
        ],
    },
    {
        id: 38,
        name: "Party Dress - Orange",
        price: 40,
        category: "women",
        size: size,
        quantity: 100,
        image: [
            "party_dress_orange_1.webp",
            "party_dress_orange_2.webp",
            "party_dress_orange_3.webp",
            "party_dress_orange_4.webp",
        ],
    },
    {
        id: 39,
        name: "Party Dress - Red",
        price: 40,
        category: "women",
        size: size,
        quantity: 100,
        image: [
            "party_dress_orange_1.webp",
            "party_dress_orange_2.webp",
            "party_dress_orange_3.webp",
            "party_dress_orange_4.webp",
        ],
    },
    {
        id: 40,
        name: "Black Miniskirt",
        price: 25,
        category: "",
        size: size,
        quantity: 100,
        image: [
            "black_miniskirt_1.webp",
            "black_miniskirt_2.webp",
            "black_miniskirt_3.webp",
            "black_miniskirt_4.webp",
        ],
    },
    {
        id: 41,
        name: "Golden Miniskirt",
        price: 25,
        category: "women",
        size: size,
        quantity: 100,
        image: [
            "gold_miniskirt_1.webp",
            "gold_miniskirt_2.webp",
            "gold_miniskirt_3.webp",
            "gold_miniskirt_4.webp",
        ],
    },
    {
        id: 42,
        name: "Red Miniskirt",
        price: 25,
        category: "women",
        size: size,
        quantity: 100,
        image: [
            "red_miniskirt_1.webp",
            "red_miniskirt_2.webp",
            "red_miniskirt_3.webp",
            "red_miniskirt_4.webp",
        ],
    },
];