
interface Iproduct {
    id: number
    productName: string,
    price: number,
    category: string,
    size: string[] | null,
    quantity: number,
    image: string[],
    tag?: string[],
    description?: string,
}

const category = ["men", "women", "accessory"];
const size = ["S", "M", "L", "XL"]
export let productData: Iproduct[] = [
    {
        id: 1,
        productName: "Basic White Tee",
        price: 10,
        category: "men",
        size: size,
        quantity: 100,
        image: [
            "Men/shirt/basic_white_tee/basic_white_tee_1.webp",
            "Men/shirt/basic_white_tee/basic_white_tee_2.webp",
            "Men/shirt/basic_white_tee/basic_white_tee_preview_1.webp"
        ],
    },
    {
        id: 2,
        productName: "Basic Black Tee",
        price: 10,
        category: "men",
        size: size,
        quantity: 100,
        image: [
            "Men/shirt/basic_black_tee/basic_black_tee_1.webp",
            "Men/shirt/basic_black_tee/basic_black_tee_2.webp",
            "Men/shirt/basic_black_tee/basic_black_tee_preview_1.webp"
        ],
    },
    {
        id: 3,
        productName: "Black Shirt",
        price: 20,
        category: "men",
        size: size,
        quantity: 100,
        image: [
            "Men/shirt/black_shirt/black_shirt_1.webp",
            "Men/shirt/black_shirt/black_shirt_2.webp",
            "Men/shirt/black_shirt/black_shirt_preview_1.webp",
            "Men/shirt/black_shirt/black_shirt_preview_2.webp",
            "Men/shirt/black_shirt/black_shirt_preview_3.webp"
        ],
    },
    {
        id: 4,
        productName: "The Path T-Shirt",
        price: 15,
        category: "men",
        size: size,
        quantity: 100,
        image: [
            "Men/shirt/thepath/thepath_1.webp",
            "Men/shirt/thepath/thepath_2.webp",
            "Men/shirt/thepath/thepath_preview_1.webp",
            "Men/shirt/thepath/thepath_preview_2.webp",
            "Men/shirt/thepath/thepath_preview_3.webp"
        ],
    },
    {
        id: 5,
        productName: "White Shirt",
        price: 20,
        category: "men",
        size: size,
        quantity: 100,
        image: [
            "Men/shirt/white_shirt/white_shirt_1.webp",
            "Men/shirt/white_shirt/white_shirt_2.webp",
            "Men/shirt/white_shirt/white_shirt_preview_1.webp",
            "Men/shirt/white_shirt/white_shirt_preview_2.webp",
            "Men/shirt/white_shirt/white_shirt_preview_3.webp",
            "Men/shirt/white_shirt/white_shirt_preview_4.webp"
        ],
    },
    {
        id: 6,
        productName: "Young Asian T-Shirt",
        price: 15,
        category: "men",
        size: size,
        quantity: 100,
        image: [
            "Men/shirt/young_asian/young_asian_1.webp",
            "Men/shirt/young_asian/young_asian_2.webp",
            "Men/shirt/young_asian/young_asian_preview_1.webp",
            "Men/shirt/young_asian/young_asian_preview_2.webp",
        ],
    },
    {
        id: 7,
        productName: "YOLO Black Hoodie",
        price: 30,
        category: "",
        size: size,
        quantity: 100,
        image: [
            "Men/shirt/OUTERWEAR/black_hoodie/black_hoodie_1.webp",
            "Men/shirt/OUTERWEAR/black_hoodie/black_hoodie_2.webp",
            "Men/shirt/OUTERWEAR/black_hoodie/black_hoodie_preview_1.webp",
            "Men/shirt/OUTERWEAR/black_hoodie/black_hoodie_preview_2.webp",
        ],
    },
    {
        id: 8,
        productName: "SCHDTX Hoodie",
        price: 30,
        category: "men",
        size: size,
        quantity: 100,
        image: [
            "Men/shirt/OUTERWEAR/SCHDTX/SCHDTX_1.webp",
            "Men/shirt/OUTERWEAR/SCHDTX/SCHDTX_2.webp",
            "Men/shirt/OUTERWEAR/SCHDTX/SCHDTX_preview_1.webp",
            "Men/shirt/OUTERWEAR/SCHDTX/SCHDTX_preview_2.webp",
            "Men/shirt/OUTERWEAR/SCHDTX/SCHDTX_preview_3.webp"
        ],
    },
    {
        id: 9,
        productName: "Tie dye WindBreaker Hoodie",
        price: 40,
        category: "men",
        size: size,
        quantity: 100,
        image: [
            "Men/shirt/OUTERWEAR/tiedye_windbreaker/tiedye_windbreaker_1.webp",
            "Men/shirt/OUTERWEAR/tiedye_windbreaker/tiedye_windbreaker_2.webp",
            "Men/shirt/OUTERWEAR/tiedye_windbreaker/tiedye_windbreaker_preview_1.webp",
            "Men/shirt/OUTERWEAR/tiedye_windbreaker/tiedye_windbreaker_preview_2.webp",
            "Men/shirt/OUTERWEAR/tiedye_windbreaker/tiedye_windbreaker_preview_3.webp"
        ],
    },
    {
        id: 10,
        productName: "Signature Hoodie",
        price: 40,
        category: "women",
        size: size,
        quantity: 100,
        image: [
            "Men/shirt/OUTERWEAR/yellow_hoodie/yellow_hoodie_1.webp",
            "Men/shirt/OUTERWEAR/yellow_hoodie/yellow_hoodie_2.webp",
            "Men/shirt/OUTERWEAR/yellow_hoodie/yellow_hoodie_preview_1.webp",
            "Men/shirt/OUTERWEAR/yellow_hoodie/yellow_hoodie_preview_2.webp",
            "Men/shirt/OUTERWEAR/yellow_hoodie/yellow_hoodie_preview_3.webp"
        ],
    },
    {
        id: 11,
        productName: "Basic Black Shorts",
        price: 10,
        category: "men",
        size: size,
        quantity: 100,
        image: [
            "Men/pants/basic_black_shorts/basic_black_shorts_1.webp",
            "Men/pants/basic_black_shorts/basic_black_shorts_2.webp",
            "Men/pants/basic_black_shorts/basic_black_shorts_preview_1.webp",
            "Men/pants/basic_black_shorts/basic_black_shorts_preview_2.webp",
            "Men/pants/basic_black_shorts/basic_black_shorts_preview_3.webp"
        ],
    },
    {
        id: 12,
        productName: "Basic White Shorts",
        price: 12,
        category: "men",
        size: size,
        quantity: 100,
        image: [
            "Men/pants/basic_white_shorts/basic_white_shorts_1.webp",
            "Men/pants/basic_white_shorts/basic_white_shorts_2.webp",
            "Men/pants/basic_white_shorts/basic_white_shorts_preview_1.webp",
            "Men/pants/basic_white_shorts/basic_white_shorts_preview_2.webp",
            "Men/pants/basic_white_shorts/basic_white_shorts_preview_3.webp"
        ],
    },
    {
        id: 13,
        productName: "Black Fashion Jogger",
        price: 20,
        category: "men",
        size: size,
        quantity: 100,
        image: [
            "Men/pants/black_jogger/black_jogger_1.webp",
            "Men/pants/black_jogger/black_jogger_2.webp",
            "Men/pants/black_jogger/black_jogger_preview_1.webp",
            "Men/pants/black_jogger/black_jogger_preview_2.webp",
            "Men/pants/black_jogger/black_jogger_preview_3.webp"
        ],
    },
    {
        id: 14,
        productName: "Yellow Jogger",
        price: 20,
        category: "men",
        size: size,
        quantity: 100,
        image: [
            "Men/pants/yellow_jogger/yellow_jogger_1.webp",
            "Men/pants/yellow_jogger/yellow_jogger_2.webp",
            "Men/pants/yellow_jogger/yellow_jogger_preview_1.webp",
            "Men/pants/yellow_jogger/yellow_jogger_preview_2.webp",
        ],
    },
    {
        id: 15,
        productName: "Black Shorts - The Path",
        price: 15,
        category: "men",
        size: size,
        quantity: 100,
        image: [
            "Men/pants/black_shorts_thepath/black_shorts_thepath_1.webp",
            "Men/pants/black_shorts_thepath/black_shorts_thepath_2.webp",
            "Men/pants/black_shorts_thepath/black_shorts_thepath_preview_1.webp",
            "Men/pants/black_shorts_thepath/black_shorts_thepath_preview_2.webp",
            "Men/pants/black_shorts_thepath/black_shorts_thepath_preview_3.webp"
        ],
    },
    {
        id: 16,
        productName: "Blue Shorts",
        price: 10,
        category: "men",
        size: size,
        quantity: 100,
        image: [
            "Men/pants/blue_shorts/blue_shorts_1.webp",
            "Men/pants/blue_shorts/blue_shorts_2.webp",
            "Men/pants/blue_shorts/blue_shorts_preview_1.webp",
            "Men/pants/blue_shorts/blue_shorts_preview_2.webp",
            "Men/pants/blue_shorts/blue_shorts_preview_3.webp"
        ],
    },
    {
        id: 17,
        productName: "Cordugoy Pants",
        price: 15,
        category: "men",
        size: size,
        quantity: 100,
        image: [
            "Men/pants/cordugoy_pants/cordugoy_pants_1.webp",
            "Men/pants/cordugoy_pants/cordugoy_pants_2.webp",
            "Men/pants/cordugoy_pants/cordugoy_pants_preview_1.webp",
            "Men/pants/cordugoy_pants/cordugoy_pants_preview_2.webp",
            "Men/pants/cordugoy_pants/cordugoy_pants_preview_3.webp",
            "Men/pants/cordugoy_pants/cordugoy_pants_preview_4.webp"
        ],
    },
    {
        id: 18,
        productName: "Formal Long Trousers",
        price: 25,
        category: "men",
        size: size,
        quantity: 100,
        image: [
            "Men/pants/long_trousers/long_trousers_1.webp",
            "Men/pants/long_trousers/long_trousers_2.webp",
            "Men/pants/long_trousers/long_trousers_preview_1.webp",
            "Men/pants/long_trousers/long_trousers_preview_2.webp",
            "Men/pants/long_trousers/long_trousers_preview_3.webp",
            "Men/pants/long_trousers/long_trousers_preview_4.webp",
            "Men/pants/long_trousers/long_trousers_preview_5.webp",
        ],
    },
    {
        id: 19,
        productName: "Black Track Pants",
        price: 20,
        category: "men",
        size: size,
        quantity: 100,
        image: [
            "Men/pants/track_pants/track_pants_1.webp",
            "Men/pants/track_pants/track_pants_2.webp",
            "Men/pants/track_pants/track_pants_preview_1.webp",
            "Men/pants/track_pants/track_pants_preview_2.webp",
            "Men/pants/track_pants/track_pants_preview_3.webp",
            "Men/pants/track_pants/track_pants_preview_4.webp",
        ],
    },
    {
        id: 20,
        productName: "White Track Pants",
        price: 20,
        category: "men",
        size: size,
        quantity: 100,
        image: [
            "Men/pants/white_track_pants/white_track_pants_1.webp",
            "Men/pants/white_track_pants/white_track_pants_2.webp",
            "Men/pants/white_track_pants/white_track_pants_preview_1.webp",
            "Men/pants/white_track_pants/white_track_pants_preview_2.webp",
            "Men/pants/white_track_pants/white_track_pants_preview_3.webp",
            "Men/pants/white_track_pants/white_track_pants_preview_4.webp",
        ],
    },
    {
        id: 21,
        productName: "Westside Shorts",
        price: 15,
        category: "men",
        size: size,
        quantity: 100,
        image: [
            "Men/pants/westside_shorts/westside_shorts_1.webp",
            "Men/pants/westside_shorts/westside_shorts_2.webp",
            "Men/pants/westside_shorts/westside_shorts_preview_1.webp",
            "Men/pants/westside_shorts/westside_shorts_preview_2.webp",
            "Men/pants/westside_shorts/westside_shorts_preview_3.webp",
        ],
    },
    {
        id: 22,
        productName: "Family Cap",
        price: 10,
        category: "accessory",
        size: size,
        quantity: 50,
        image: [
            "Accessory/cap/family_cap/family_cap_1.webp",
            "Accessory/cap/family_cap/family_cap_2.webp",
            "Accessory/cap/family_cap/family_cap_3.webp",
        ],
    },
    {
        id: 23,
        productName: "High top Beanine",
        price: 13,
        category: "accessory",
        size: size,
        quantity: 50,
        image: [
            "Accessory/cap/high_top_beanie/high_top_beanie_1.webp",
            "Accessory/cap/high_top_beanie/high_top_beanie_2.webp",
            "Accessory/cap/high_top_beanie/high_top_beanie_3.webp",
            "Accessory/cap/high_top_beanie/high_top_beanie_4.webp",
            "Accessory/cap/high_top_beanie/high_top_beanie_5.webp",
        ],
    },
    {
        id: 24,
        productName: "Skull Beanie - Blue Edition",
        price: 15,
        category: "accessory",
        size: size,
        quantity: 50,
        image: [
            "Accessory/cap/skull_beanie_blue/skull_beanie_blue_1.webp",
            "Accessory/cap/skull_beanie_blue/skull_beanie_blue_2.webp",
            "Accessory/cap/skull_beanie_blue/skull_beanie_blue_3.webp",
            "Accessory/cap/skull_beanie_blue/skull_beanie_blue_4.webp",
        ],
    },
    {
        id: 25,
        productName: "Skull Beanie - Orange Edition",
        price: 15,
        category: "accessory",
        size: size,
        quantity: 50,
        image: [
            "Accessory/cap/skull_beanie/orange/skull_beanie_orange_1.webp",
            "Accessory/cap/skull_beanie/orange/skull_beanie_orange_2.webp",
            "Accessory/cap/skull_beanie/orange/skull_beanie_orange_3.webp",
            "Accessory/cap/skull_beanie/orange/skull_beanie_orange_4.webp",
        ],
    },
    {
        id: 26,
        productName: "Original Cap - Yellow",
        price: 10,
        category: "accessory",
        size: size,
        quantity: 50,
        image: [
            "Accessory/cap/original_cap_yellow/original_cap_yellow_1.webp",
            "Accessory/cap/original_cap_yellow/original_cap_yellow_2.webp",
            "Accessory/cap/original_cap_yellow/original_cap_yellow_3.webp",
        ],
    },
    {
        id: 27,
        productName: "SCHDTX Cap",
        price: 15,
        category: "accessory",
        size: size,
        quantity: 50,
        image: [
            "Accessory/cap/SCHDTX_cap/schdtx_cap_1.webp",
            "Accessory/cap/SCHDTX_cap/schdtx_cap_2.webp",
            "Accessory/cap/SCHDTX_cap/schdtx_cap_3.webp",
            "Accessory/cap/SCHDTX_cap/schdtx_cap_4.webp",
        ],
    },
    {
        id: 28,
        productName: "SCHDTX Cap - White",
        price: 15,
        category: "accessory",
        size: size,
        quantity: 50,
        image: [
            "Accessory/cap/SCHDTX_cap_white/schdtx_cap_white_1.webp",
            "Accessory/cap/SCHDTX_cap_white/schdtx_cap_white_2.webp",
            "Accessory/cap/SCHDTX_cap_white/schdtx_cap_white_3.webp",
            "Accessory/cap/SCHDTX_cap_white/schdtx_cap_white_4.webp",
        ],
    },
    {
        id: 29,
        productName: "Messenger Bag",
        price: 60,
        category: "accessory",
        size: null,
        quantity: 50,
        image: [
            "Accessory/bag/messenger_bag/messenger_bag_1.webp",
            "Accessory/bag/messenger_bag/messenger_bag_2.webp",
            "Accessory/bag/messenger_bag/messenger_bag_3.webp",
            "Accessory/bag/messenger_bag/messenger_bag_4.webp",
            "Accessory/bag/messenger_bag/messenger_bag_5.webp",
            "Accessory/bag/messenger_bag/messenger_bag_6.webp",
        ],
    },
    {
        id: 30,
        productName: "Shoulder bag - Black Colorway",
        price: 35,
        category: "accessory",
        size: null,
        quantity: 50,
        image: [
            "Accessory/bag/shoulder_bag/shoulder_bag_black_1.webp",
            "Accessory/bag/shoulder_bag/shoulder_bag_black_2.webp",
            "Accessory/bag/shoulder_bag/shoulder_bag_black_3.webp",
            "Accessory/bag/shoulder_bag/shoulder_bag_black_4.webp",
            "Accessory/bag/shoulder_bag/shoulder_bag_black_5.webp",
        ],
    },
    {
        id: 31,
        productName: "Shoulder bag - Cream Colorway",
        price: 35,
        category: "accessory",
        size: null,
        quantity: 50,
        image: [
            "Accessory/bag/shoulder_bag_cream/shoulder_bag_cream_1.webp",
            "Accessory/bag/shoulder_bag_cream/shoulder_bag_cream_2.webp",
            "Accessory/bag/shoulder_bag_cream/shoulder_bag_cream_3.webp",
            "Accessory/bag/shoulder_bag_cream/shoulder_bag_cream_4.webp",
            "Accessory/bag/shoulder_bag_cream/shoulder_bag_cream_5.webp",
        ],
    },
    {
        id: 32,
        productName: "Westside Crossbody Sporty Bag",
        price: 30,
        category: "accessory",
        size: null,
        quantity: 50,
        image: [
            "Accessory/bag/westside_crossbody/westside_crossbody_1.webp",
            "Accessory/bag/westside_crossbody/westside_crossbody_2.webp",
            "Accessory/bag/westside_crossbody/westside_crossbody_3.webp",
            "Accessory/bag/westside_crossbody/westside_crossbody_4.webp",
            "Accessory/bag/westside_crossbody/westside_crossbody_5.webp",
        ],
    },
    {
        id: 33,
        productName: "StyleShop's Signature Backpack",
        price: 120,
        category: "accessory",
        size: null,
        quantity: 50,
        image: [
            "Accessory/backpack/backpack_1.webp",
            "Accessory/backpack/backpack_2.webp",
            "Accessory/backpack/backpack_3.webp",
            "Accessory/backpack/backpack_4.webp",
            "Accessory/backpack/backpack_5.webp",
        ],
    },
    {
        id: 34,
        productName: "Black Kaki Dress",
        price: 20,
        category: "women",
        size: size,
        quantity: 100,
        image: [
            "Women/dress/black_kaki_dress/black_kaki_dress_1.webp",
            "Women/dress/black_kaki_dress/black_kaki_dress_2.webp",
            "Women/dress/black_kaki_dress/black_kaki_dress_3.webp",
            "Women/dress/black_kaki_dress/black_kaki_dress_4.webp",
        ],
    },
    {
        id: 35,
        productName: "Flower Pattern Dress",
        price: 15,
        category: "women",
        size: size,
        quantity: 100,
        image: [
            "Women/dress/flower_dress/flower_dress_1.webp",
            "Women/dress/flower_dress/flower_dress_2.webp",
            "Women/dress/flower_dress/flower_dress_3.webp",
            "Women/dress/flower_dress/flower_dress_4.webp",
        ],
    },
    {
        id: 36,
        productName: "Yellow Twist Dress",
        price: 20,
        category: "women",
        size: size,
        quantity: 100,
        image: [
            "Women/dress/yellow_twist_dress/yellow_twist_dress_1.webp",
            "Women/dress/yellow_twist_dress/yellow_twist_dress_2.webp",
            "Women/dress/yellow_twist_dress/yellow_twist_dress_3.webp",
            "Women/dress/yellow_twist_dress/yellow_twist_dress_4.webp",
        ],
    },
    {
        id: 37,
        productName: "Party Dress - Flower Pattern",
        price: 45,
        category: "women",
        size: size,
        quantity: 100,
        image: [
            "Women/dress/party_dress_flower/party_dress_flower_1.webp",
            "Women/dress/party_dress_flower/party_dress_flower_2.webp",
            "Women/dress/party_dress_flower/party_dress_flower_3.webp",
            "Women/dress/party_dress_flower/party_dress_flower_4.webp",
        ],
    },
    {
        id: 38,
        productName: "Party Dress - Orange",
        price: 40,
        category: "women",
        size: size,
        quantity: 100,
        image: [
            "Women/dress/party_dress_orange/party_dress_orange_1.webp",
            "Women/dress/party_dress_orange/party_dress_orange_2.webp",
            "Women/dress/party_dress_orange/party_dress_orange_3.webp",
            "Women/dress/party_dress_orange/party_dress_orange_4.webp",
        ],
    },
    {
        id: 39,
        productName: "Party Dress - Red",
        price: 40,
        category: "women",
        size: size,
        quantity: 100,
        image: [
            "Women/dress/party_dress_red/party_dress_red_1.webp",
            "Women/dress/party_dress_red/party_dress_red_2.webp",
            "Women/dress/party_dress_red/party_dress_red_3.webp",
            "Women/dress/party_dress_red/party_dress_red_4.webp",
        ],
    },
    {
        id: 40,
        productName: "Black Miniskirt",
        price: 25,
        category: "",
        size: size,
        quantity: 100,
        image: [
            "Women/skirt/black_miniskirt/black_miniskirt_1.webp",
            "Women/skirt/black_miniskirt/black_miniskirt_2.webp",
            "Women/skirt/black_miniskirt/black_miniskirt_3.webp",
            "Women/skirt/black_miniskirt/black_miniskirt_4.webp",
        ],
    },
    {
        id: 41,
        productName: "Golden Miniskirt",
        price: 25,
        category: "women",
        size: size,
        quantity: 100,
        image: [
            "Women/skirt/gold_miniskirt/gold_miniskirt_1.webp",
            "Women/skirt/gold_miniskirt/gold_miniskirt_2.webp",
            "Women/skirt/gold_miniskirt/gold_miniskirt_3.webp",
            "Women/skirt/gold_miniskirt/gold_miniskirt_4.webp",
        ],
    },
    {
        id: 42,
        productName: "Red Miniskirt",
        price: 25,
        category: "women",
        size: size,
        quantity: 100,
        image: [
            "Women/skirt/red_miniskirt/red_miniskirt_1.webp",
            "Women/skirt/red_miniskirt/red_miniskirt_2.webp",
            "Women/skirt/red_miniskirt/red_miniskirt_3.webp",
            "Women/skirt/red_miniskirt/red_miniskirt_4.webp",
        ],
    },
];